#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: 2

registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - maven-central
    allow:
      # Quarkiverse extensions
      - dependency-name: "io.quarkiverse.*:*"
      # Other third party extensions
      - dependency-name: "com.datastax.oss.quarkus:cassandra-quarkus-bom"
      - dependency-name: "com.hazelcast:quarkus-hazelcast-client-bom"
      - dependency-name: "com.squareup.okhttp3:okhttp"
      - dependency-name: "io.debezium:debezum-bom"
      - dependency-name: "io.swagger.codegen.v3:swagger-codegen-generators"
      - dependency-name: "org.amqphub.quarkus:quarkus-qpid-jms-bom"
      - dependency-name: "org.jolokia:jolokia-agent-jvm"
      # Test dependencies
      - dependency-name: "org.wiremock:wiremock-standalone"
      - dependency-name: "com.unboundid:unboundid-ldapsdk"
      - dependency-name: "io.smallrye.certs:smallrye-certificate-generator-junit5"
      - dependency-name: "org.hamcrest:hamcrest"
      - dependency-name: "org.hamcrest:hamcrest-core"
      - dependency-name: "org.seleniumhq.selenium:htmlunit-driver"
      - dependency-name: "org.xmlunit:xmlunit-core"
      - dependency-name: "org.zeroturnaround:zt-exec"
      - dependency-name: "com.microsoft.graph:microsoft-graph"
      - dependency-name: "com.microsoft.graph:microsoft-graph-auth"
      # Maven plugins
      - dependency-name: "*:*-maven-plugin"
      - dependency-name: "org.apache.maven.plugins:*"
    ignore:
      # Maven plugins
      # Quarkus is upgraded manually
      - dependency-name: "io.quarkus:quarkus-*-maven-plugin"
      # Automatically aligned with the Quarkus Jandex version
      - dependency-name: "io.smallrye:jandex-maven-plugin"
      # Camel is upgraded manually
      - dependency-name: "org.apache.camel.maven:*"
      # To be kept manually in alignment with the enforcer API version used in quarkus-enforcer-rules
      - dependency-name: "org.apache.maven.plugins:maven-enforcer-plugin"
