#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

site:
  title: Apache Camel extensions for Quarkus
  url: https://camel.apache.org
  start_page: camel-quarkus::index.adoc

content:
  sources:
  - url: ./../
    branches: HEAD
    start_path: docs

  - url: https://github.com/apache/camel-quarkus-examples.git
    branches: main
    start_path: docs

# The version/branch of main camel 'components' this version of camel-quarkus uses
  - url: https://github.com/apache/camel.git
    branches:
      - camel-3.12.x # replace ${camel.docs.branch}
    start_paths:
      # eip
      - core/camel-core-engine/src/main/docs
      # main components doc
      - docs/components

# There is only one version of the user manual
  - url: https://github.com/apache/camel.git
    branches:
      - main
    start_paths:
      - docs/user-manual

# The camel-spring-boot version corresponding to the main camel 'components' version/branch
  - url: https://github.com/apache/camel-spring-boot.git
    branches:
      - camel-spring-boot-3.12.x # replace ${camel.sb.docs.branch}
    start_path: docs/components

asciidoc:
  extensions:
    - "@djencks/asciidoctor-antora-indexer"
  attributes:
    eip-vc: latest@components

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./target/site

urls:
  redirect_facility: httpd

runtime:
  log:
    level: warn
    failure_level: warn

pipeline:
  extensions:
    - require: '@djencks/asciidoctor-jsonpath'
